[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[functions]
  included_files = ["templates/**", "database.db"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
